### PR TITLE
Fix: not all code paths return a value with "--noImplicitReturns"

### PR DESCRIPTION
**Pull request by ClementNerma**

### CODE REVIEW

**Comment by antonmedv** [comment]
Is it still valid as not d.ts is ready?

**Comment by ClementNerma** [comment]
What do you mean?

**Comment by antonmedv** [comment]
I don't see an error in build tsc. Why this PR?

**Comment by ClementNerma** [comment]
The `tsconfig.json` options are not inherited if they aren't specified ; if you use CodeJar in a project that sets the `noImplicitReturns` option to `true`, the compiler will complain that CodeJar isn't following this rule.

**Comment by antonmedv** [comment]
But codejar provides d.fs file. Should it be used?

**Comment by ClementNerma** [comment]
I just checked my old code and I remember I was not importing CodeJar as a third-party NPM package but instead I directly put the CodeJar's source code in my own project to avoid problems I had with NPM.
So this may not apply to the NPM version indeed 🤔

**Pull request closed without merging**
