### PR TITLE
[WIP] Improve line numbers feature & better carriage return compatibility

### LINKED ISSUE #19: New line issue in Firefox
In Firefox when I press on Enter the cursor stays on the current line, if I press a key then it appears on a new line but it's still very disturbing.

Everything is fine in Chrome though

Happens on the example page when I remove all the code of one of the editors and write some new

### LINKED ISSUE #22: Deleting last line
When I delete all characters in the last line, the cursor moves up to the previous line, which is different from the typical behavior of most editors. In all editors that I am used to, the cursor still stays in the last line without moving up. I wonder whether this behavior is intentional and whether there is any way to change it (or add an option to let it behave differently).

Jun-16-2020 09-32-42

### PR DESCRIPTION
**Pull request by sirkadirov**
### DONE:
- Fix line counting issue
- Disable line numbers selection
- Temporary disable line numbers background
- Force X and Y overflow when using line numbers
- Make line numbers bar scrollable
- Improve line breaks (use universal `\r\n` instead of `\n`

### TODO:
- Try to fix #19
- Try to fix #22
- Static line numbers bar (now broken) - **help needed**
- Implement current line highlighting
- Look for breaking changes

**Work in progress - do not merge 😅!** Comments and suggestions welcome.

### CODE REVIEW

**Comment by antonmedv** [comment]
Awesome! 👏 
Also, it will be cool to have something online to see how your changes work. Maybe in playground.

**Comment by sirkadirov** [comment]
@antonmedv Sure, I'll make a demo later. Any ideas on good online playground? :)

**Comment by antonmedv** [comment]
I usually upload everything to my site.

**Comment by antonmedv** [comment]
So any news?

**Comment by antonmedv** [comment]
Any progress?

**Comment by hgs3** [comment]
> Static line numbers bar (now broken) - help needed

Line numbers were fixed in [this commit](https://github.com/antonmedv/codejar/commit/6a450305298e48415c46a015b2da10b6504e38fe).

> Improve line breaks (use universal `\r\n` instead of `\n`)

I'm not savvy enough to know when Windows line endings are universally preferred over Unix line endings, but if Unix line endings are kept, then [this regex](https://github.com/antonmedv/codejar/pull/26/files#diff-e457d7d3a87ae1c2bf4d1ff548822048f751fb0c5fb514b308690d4bd7317876L31-R32) can be simplified to:

```javascript
code.split(/\n/).length + (code.endsWith('\n') ? 0 : 1)
```

Either way, it fixes the issue where line numbers aren't added to the end of the editor.

@antonmedv Here are before and after gif's. Observe the line numbers as new lines are added. The first gif was captured using the latest master branch and second gif was captured with the regex fix:

before_fix
after_fix

**Comment by antonmedv** [comment]
Any progress? Someone what to continue from this PR?

**Pull request closed without merging**
